# Dockerfile.mcp
FROM python:3.12.3-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

COPY requirements_docker.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements_docker.txt

COPY . .

CMD ["python", "mcp_servers\run_mcp_servers.py"]