version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    restart: always

  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    volumes:
      - .:/code
    restart: always
